### ISSUE TITLE
Milestone 1: Enable creating & editing whiteboard in the Rocket.Chat

### ISSUE THREAD

**Issue by shiqimei** [RocketChat/Apps.Whiteboard#5]
- [x] 1. implement slashcommand `/whiteboard new` -> create a board record in persistence -> send the rich block message (with a empty white background image and a Edit link);
- [x] 2. Rewrite `/excalidraw` to `[GET] board/<boardId>` route
- [x] 3. implement `[POST] board/<boardId>/update`, post board data and board png preview image whenever board changes in debounce;
- [x] 4. implement `[GET] /board/<boardId>/get` route (for gettting route data). in client, get the board data in useEffect(() => {}, []) and render the data to board.
